apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-fe
spec:
  replicas: 3

  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1

  selector:
    matchLabels:
      app: app-fe

  template:
    metadata:
      labels:
        app: app-fe
    spec:
      containers:
        - name: app-fe
          image: aksh76120/app-fe:720c8f56ab7d46057fe18a7429c442532676bc67
          imagePullPolicy: Always
          ports:
            - containerPort: 80

          readinessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 5
            periodSeconds: 10
