apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-fe
spec:
  replicas: 2
  selector:
    matchLabels:
      app: app-fe
  template:
    metadata:
      labels:
        app: app-fe
    spec:
      containers:
        - name: app-fe
          image: aksh76120/app-fe:e28ce014d39f21b1cf2f273a51c0a30249c51dff
          ports:
            - containerPort: 80
