apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-fe
spec:
  replicas: 2
  selector:
    matchLabels:
      app: app-fe
  template:
    metadata:
      labels:
        app: app-fe
    spec:
      containers:
        - name: app-fe
          image: aksh76120/app-fe:5873a4cecd8adaf0b7a346645968754367cc7c64
          ports:
            - containerPort: 80
