apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: app-fe-ingress
spec:
  ingressClassName: nginx
  rules:
    - host: app-fe.local # This is the URL you will use
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: app-fe-service
                port:
                  number: 80 # Matches the 'port' in your Service
