apiVersion: v1
kind: Service
metadata:
  name: app-fe-service
spec:
  type: ClusterIP # Use ClusterIP when using Ingress; NodePort isn't necessary
  selector:
    app: app-fe
  ports:
    - port: 80
      targetPort: 80
